// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/hpc.proto

package hpc

import (
	fmt "fmt"
	_ "github.com/essayZW/hpcmanager/gateway/proto"
	proto1 "github.com/essayZW/hpcmanager/proto"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Hpc service

func NewHpcEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Hpc service

type HpcService interface {
	Ping(ctx context.Context, in *proto1.Empty, opts ...client.CallOption) (*proto1.PingResponse, error)
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...client.CallOption) (*CreateGroupResponse, error)
}

type hpcService struct {
	c    client.Client
	name string
}

func NewHpcService(name string, c client.Client) HpcService {
	return &hpcService{
		c:    c,
		name: name,
	}
}

func (c *hpcService) Ping(ctx context.Context, in *proto1.Empty, opts ...client.CallOption) (*proto1.PingResponse, error) {
	req := c.c.NewRequest(c.name, "Hpc.Ping", in)
	out := new(proto1.PingResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hpcService) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...client.CallOption) (*CreateGroupResponse, error) {
	req := c.c.NewRequest(c.name, "Hpc.CreateGroup", in)
	out := new(CreateGroupResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hpc service

type HpcHandler interface {
	Ping(context.Context, *proto1.Empty, *proto1.PingResponse) error
	CreateGroup(context.Context, *CreateGroupRequest, *CreateGroupResponse) error
}

func RegisterHpcHandler(s server.Server, hdlr HpcHandler, opts ...server.HandlerOption) error {
	type hpc interface {
		Ping(ctx context.Context, in *proto1.Empty, out *proto1.PingResponse) error
		CreateGroup(ctx context.Context, in *CreateGroupRequest, out *CreateGroupResponse) error
	}
	type Hpc struct {
		hpc
	}
	h := &hpcHandler{hdlr}
	return s.Handle(s.NewHandler(&Hpc{h}, opts...))
}

type hpcHandler struct {
	HpcHandler
}

func (h *hpcHandler) Ping(ctx context.Context, in *proto1.Empty, out *proto1.PingResponse) error {
	return h.HpcHandler.Ping(ctx, in, out)
}

func (h *hpcHandler) CreateGroup(ctx context.Context, in *CreateGroupRequest, out *CreateGroupResponse) error {
	return h.HpcHandler.CreateGroup(ctx, in, out)
}
