/* eslint-disable prettier/prettier */
// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside'];
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElFooter: typeof import('element-plus/es')['ElFooter'];
    ElHeader: typeof import('element-plus/es')['ElHeader'];
    ElImage: typeof import('element-plus/es')['ElImage'];
    ElMain: typeof import('element-plus/es')['ElMain'];
    MainView: typeof import('./src/components/pages/MainView.vue')['default'];
    NotFound: typeof import('./src/components/pages/NotFound.vue')['default'];
  }
}

export {};
